[project]
name = "opentes-integration"
version = "0.1.0"
description = "Local Python environment for OpenTES simulator integration."
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "pade-agents",
    "grid-opentes",
    "mosaik==3.5.0",
    "mosaik-api==3.0.6",
    "mosaik-api-v3>=3.0.13,<3.1",
    "mosaik-csv==2.0.1",
    "opender==2.1.6",
    "pandas>=2.3.2",
    "matplotlib>=3.10.0",
    "py-dss-interface>=2.3.0",
    "pyzmq>=26.0.3,<28",
    "setuptools==69.5.1",
]

[tool.uv]
package = false

[tool.uv.sources]
pade-agents = { path = "simulators/pade-opentes", editable = true }
grid-opentes = { path = "simulators/grid-opentes", editable = true }
